import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<script
					id="usercentrics-cmp"
					data-settings-id="SIIm5BrSq"
					src="https://app.usercentrics.eu/browser-ui/latest/loader.js"
					async
				></script>
				<meta data-privacy-proxy-server="https://privacy-proxy-server.usercentrics.eu"></meta>

				{/* base stuff */}
				<link
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-base/master/dist/critical.css"
					rel="stylesheet"
				/>
				<link
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-base/master/dist/variables.css"
					rel="stylesheet"
				/>
				<link
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-base/master/dist/css-base.css"
					rel="stylesheet"
				/>
				<script
					src="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-base/master/dist/css-base.js"
					type="module"
					defer
				></script>

				{/* gbw-uc */}
				<link
					rel="stylesheet"
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-uc/master/public/bundle/bundle.css"
				/>
				<script
					type="module"
					src="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-uc/master/public/bundle/bundle.esm.js"
					defer
				></script>
				{/* <script type="module" src="http://localhost:3333/public/bundle/bundle.esm.js" defer></script> */}

				{/* mm-image */}
				<link
					rel="stylesheet"
					href="https://frontend.webpipeline.messe-muenchen.de/webp/mm-image/master/public/bundle/bundle.css"
				/>
				<script
					type="module"
					src="https://frontend.webpipeline.messe-muenchen.de/webp/mm-image/master/public/bundle/bundle.esm.js"
					defer
				></script>

				{/* gbw-icons */}
				<link
					rel="stylesheet"
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-icons/master/public/bundle/bundle.css"
				/>
				<script
					type="module"
					src="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-icons/master/public/bundle/bundle.esm.js"
					defer
				></script>

				{/* gbw-video */}
				<link
					rel="stylesheet"
					href="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-video/master/public/bundle/bundle.css"
				/>
				<script
					src="https://frontend.webpipeline.messe-muenchen.de/webp/gbw-video/master/public/bundle/bundle.esm.js"
					type="module"
					defer
				></script>
				{/* <script type="module" src="http://localhost:3334/public/bundle/bundle.esm.js" defer></script> */}

				{/* gbw-uc vars */}
				<script
					dangerouslySetInnerHTML={{
						__html: `var gbwUcText = {
              adition: {
                optIn: {
                  t_headline: "Opt-In (adition)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "anzeigen",
                },
                optOut: {
                  t_headline: "Opt-Out (adition)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "nicht mehr anzeigen",
                },
              },
              podigee: {
                optIn: {
                  t_headline: "Opt-In (podigee)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "anzeigen",
                },
                optOut: {
                  t_headline: "Opt-Out (podigee)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "nicht mehr anzeigen",
                },
              },
              movingimage: {
                optIn: {
                  t_headline: "Opt-In (movingimage)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "anzeigen",
                },
                optOut: {
                  t_headline: "Opt-Out (movingimage)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "nicht mehr anzeigen",
                },
              },
              "youtube-video": {
                optIn: {
                  t_headline: "",
                  t_text: 'Durch Akzeptieren stimmen Sie einerseits der Verwendung von Cookies und anderen Technologien zur Verarbeitung Ihrer personenbezogenen Daten als solche sowie andererseits der Datenübermittlung in die USA zu. Sie finden weitere Informationen, wenn Sie <a href="#">hier</a> klicken.',
                  t_label: "Akzeptieren und Video anzeigen",
                },
                optOut: {
                  t_headline: "",
                  t_text: 'Mehr dazu in unseren <a href="#">Datenschutzhinweisen</a>.',
                  t_label: "YouTube Videos nicht mehr anzeigen",
                },
              },
              "google-maps": {
                optIn: {
                  t_headline: "Opt-In (google-maps)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "anzeigen",
                },
                optOut: {
                  t_headline: "Opt-Out (google-maps)",
                  t_text: 'Lorem ipsum <a href="#" target="_blank">hier</a> dolor.',
                  t_label: "nicht mehr anzeigen",
                },
              },
            }`,
					}}
				></script>
			</head>

			<body className={inter.className}>{children}</body>
		</html>
	);
}
